### ISSUE TITLE
indra-git fails to detect repository checkout

### ISSUE THREAD

**Issue by i509VCB** [KyoriPowered/indra#30]
zml pointed me here so here I am.

Suspect commit: https://github.com/QuiltMC/yarn/commit/7763418842b1b751ec8fcba8bde1aea24d4aaa78 and github action for suspect: https://github.com/QuiltMC/yarn/runs/2462092542

Action script at that commit: https://github.com/QuiltMC/yarn/blob/7763418842b1b751ec8fcba8bde1aea24d4aaa78/.github/workflows/publish.yml

The script runs Java in docker.

**Comment by zml2008** [comment]
After some further investigation, it appears that this issue is due to a quirk on GH's end -- if `git` is not on the `PATH` of a docker container, the checkout action will perform a web checkout, discarding any git repo information. The documentation will be updated to provide a warning about this issue.
